apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          # image: server-backend:latest
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - containerPort: 8001

          startupProbe:
            httpGet:
             path: /health
             port: 8001
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 20  

          readinessProbe:
           httpGet:
            path: /health
            port: 8001
           initialDelaySeconds: 20
           periodSeconds: 10
           timeoutSeconds: 3
           failureThreshold: 6

          livenessProbe:
           httpGet:
            path: /health
            port: 8001
           initialDelaySeconds: 40
           periodSeconds: 10
           timeoutSeconds: 3
           failureThreshold: 3


          resources:
            requests:
             memory: "256Mi"
             cpu: "200m"
            limits:
             memory: "512Mi"
             cpu: "1000m"

          envFrom:
            - secretRef:
                name: backend-secrets