apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: 3

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          # image: server-backend:latest
          image: ghcr.io/sandram92/server-backend:5bdaffe5ee08265f7a9efe14c4e7b97c5a4519db
          imagePullPolicy: Always

          ports:
            - containerPort: 8001

          startupProbe:
            httpGet:
             path: /health
             port: 8001
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 20  

          readinessProbe:
           httpGet:
            path: /health
            port: 8001
           initialDelaySeconds: 20
           periodSeconds: 10
           timeoutSeconds: 3
           failureThreshold: 6

          livenessProbe:
           httpGet:
            path: /health
            port: 8001
           initialDelaySeconds: 40
           periodSeconds: 10
           timeoutSeconds: 3
           failureThreshold: 3


          resources:
            requests:
             memory: "256Mi"
             cpu: "200m"
            limits:
             memory: "512Mi"
             cpu: "1000m"

          envFrom:
            - secretRef:
                name: backend-secrets
            - configMapRef:
                name: backend-config