apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  replicas: 3

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: ghcr.io/sandram92/server-frontend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: REACT_APP_API_PROXY
              value: http://backend:8001